name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        deno: [1.0.5, 1.1.3, 1.2.2]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: denolib/setup-deno@master
      with:
        deno-version: ${{ matrix.deno }}
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install typescript eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin tsc-silent --save-dev
    - run: ./node_modules/.bin/eslint **/**.ts --ext .ts
    - run: deno lint --unstable
      if: startsWith(matrix.deno, '1.2')
    - run: deno install -Af denox.ts
    - run: deno test -A --failfast src/ test/
